In [27]:
import json
import numpy as np
import pandas as pd

In [40]:
with open("results/experiment_tag_seed_0.json", "r") as f:
    data = json.load(f)

no_regs_list = []
l2s_list = []
l1s_list = []
dropouts_list = []
input_noises_list = []
mixups_list = []
for dataset in data:
    no_regs = data[dataset]["no_reg"]
    no_regs_mean_test_loss = np.mean([no_regs[i]["test_loss"] for i in no_regs])
    no_regs_list.append(no_regs_mean_test_loss)

    l2s = data[dataset]["l2"]
    l2s_mean_test_loss = np.mean([l2s[i]["test_loss"] for i in l2s])
    l2s_list.append(l2s_mean_test_loss)

    l1s = data[dataset]["l1"]
    l1s_mean_test_loss = np.mean([l1s[i]["test_loss"] for i in l1s])
    l1s_list.append(l1s_mean_test_loss)

    dropouts = data[dataset]["dropout"]
    dropouts_mean_test_loss = np.mean([dropouts[i]["test_loss"] for i in dropouts])
    dropouts_list.append(dropouts_mean_test_loss)

    input_noises = data[dataset]["input_noise"]
    input_noises_mean_test_loss = np.mean([input_noises[i]["test_loss"] for i in input_noises])
    input_noises_list.append(input_noises_mean_test_loss)

    mixups = data[dataset]["mixup"]
    mixups_mean_test_loss = np.mean([mixups[i]["test_loss"] for i in mixups])
    mixups_list.append(mixups_mean_test_loss)

dict_keys(['student', 'bioconcentration', 'facebook', 'wine', 'abalone', 'skillcraft', 'weather', 'forest', 'protein', 'heart', 'breast', 'cervical', 'credit', 'hcv', 'tumor', 'soybean', 'australian', 'entrance', 'thoracic'])

In [41]:
df = pd.DataFrame(data={
    "dataset": list(data.keys()),
    "no_reg": no_regs_list,
    "l2": l2s_list,
    "l1": l1s_list,
    "dropout": dropouts_list,
    "input_noise": input_noises_list,
    "mixup": mixups_list,
})
display(df)

,dataset,no_reg,l2,l1,dropout,input_noise,mixup
0,student,0.403136,0.431333,0.459118,0.420383,0.490025,0.457472
1,bioconcentration,0.279593,0.269233,0.500175,0.261993,0.279530,0.289461
2,facebook,0.063246,0.058221,0.878458,0.234905,0.071440,0.128290
3,wine,0.749962,0.755099,0.765392,0.764698,0.752312,0.668801
4,abalone,0.433902,0.466544,0.535881,0.486094,0.419389,0.337242
5,skillcraft,0.511271,0.475704,0.668177,0.482709,0.459798,0.410102
6,weather,0.101105,0.120978,0.385157,0.127982,0.101391,0.100346
7,forest,1.289774,1.296936,1.302579,1.298521,1.244332,1.282239
8,protein,0.812368,0.879896,0.820316,0.917430,0.818506,0.627454
9,heart,0.462550,0.515140,0.569733,0.514911,0.464972,0.408068
10,breast,0.222048,0.258974,0.273777,0.137485,0.221850,0.094291
11,cervical,0.478383,0.443377,0.429550,0.481474,0.487575,0.449424
12,credit,0.413885,0.442228,0.506324,0.411437,0.412635,0.451305
13,hcv,0.322551,0.342768,0.333872,0.306611,0.328486,0.234122
14,tumor,1.836565,2.027227,2.109335,1.845496,1.846923,1.653381
15,soybean,0.448798,0.614059,1.989554,0.312680,0.432356,0.444335
16,australian,0.439010,0.436303,0.609586,0.379585,0.409349,0.484261